<?php

/**
 * Implements hook_block_info().
 */

function my_block_block_info() {
      $block = array();
      $block['my_block'] = array(
      'info' => t('My custom block'),
       
);
      return $block;
}

/**
 * Implements hook_block_view()
 */

function my_block_block_view($delta = '') {
         $block = array();
         if  ($delta == 'my_block') {
              $block['subject'] = t('Block Subject');
         if (user_access('administer my module')) {
              $block['content'] = t('Some content of this block');
         } else { 
              $block['content'] = t('Access to view this content is denied');
               }
         }          
         return $block;
}

